env:
  contexts:
    - name: dvwa
      urls:
        - __TARGET_URL__/DVWA/
      includePaths:
        - __TARGET_URL__/DVWA/.*
      authentication:
        method: form
        parameters:
          loginPageUrl: __TARGET_URL__/DVWA/login.php
          loginRequestUrl: __TARGET_URL__/DVWA/login.php
          loginRequestBody: "username={%username%}&password={%password%}&Login=Login"
      users:
        - name: dvwa-user
          credentials:
            username: dvwa
            password: password

jobs:
  - type: spider
    parameters:
      context: dvwa
      user: dvwa-user

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      context: dvwa
      user: dvwa-user

  - type: report
    parameters:
      template: traditional-html
      reportFile: report_html.html

  - type: report
    parameters:
      template: markdown
      reportFile: report_md.md

  - type: report
    parameters:
      template: traditional-json
      reportFile: report_json.json
