name: ZAP DVWA Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: ${{ secrets.TARGET_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace TARGET_URL in zap.yaml
        run: |
          sed "s|__TARGET_URL__|${TARGET_URL}|g" .zap/zap.yaml > .zap/zap-final.yaml
          echo "Target URL: ${TARGET_URL}"

      - name: Run ZAP Automation Framework
        uses: zaproxy/action-af@v0.2.0
        with:
          plan: '.zap/zap-final.yaml'

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_md.md
            report_json.json
            zap.log
          if-no-files-found: warn
